### ISSUE TITLE
Compatibility Angular 12

### ISSUE THREAD

**Issue by spikensbror** [intbot/ng2-pdfjs-viewer#164]
Could you update the peer dependency to angular/core from ^11.0.0 to ^12.0.0? We are currently stuck with our update of Angular until this is resolved.

**Comment by ankurkoul92** [comment]
Yes, even we want to upgrade our project to angular 12. But are stuck because of `ng2-pdfjs-viewer` package.

Let me know if I can be of some help on this.

**Comment by petebacondarwin** [comment]
If the library works with v12 of Angular, then you could just ignore this peer dependency constraint @ankurkoul92. But you need to test it.

**Comment by AnsonWooNexify** [comment]
I tried in v12 of Angular, it shown nothing on the screen, anyone like me?

**Comment by breadcrumbe** [comment]
> I tried in v12 of Angular, it shown nothing on the screen, anyone like me?

I have just upgraded one of my projects from Angular 11 to Angular 12 and I have ng2-pdfjs-viewer 6.11 - which is working 100% - although it did complain about the dep.

**Comment by rogerfar** [comment]
How about v13?

**Comment by logerk46** [comment]
@rogerfar hi,

I have now tried ng2-pdfjs-viewer (6.0.2) with version 13 of Angular and everything works.

**Comment by konstantinschuette** [comment]
> @rogerfar hi,
> 
> I have now tried ng2-pdfjs-viewer (6.0.2) with version 13 of Angular and everything works.

![image](https://user-images.githubusercontent.com/18708105/151791471-2ebf1d32-2b6c-484a-a774-db6468d8ae04.png)

Are you sure about that?

**Comment by pmenze** [comment]
Same here. I was using nodejs 12 with angular 13 and ng2-pdfjs-viewer (6.0.2). after updating to node 16 it shows the same error as in the previous post by @konstantinschuette

**Comment by konstantinschuette** [comment]
> Same here. I was using nodejs 12 with angular 13 and ng2-pdfjs-viewer (6.0.2). after updating to node 16 it shows the same error as in the previous post by @konstantinschuette

It seems like this project is inactive or rarely maintained.
The package uses Angular 11, soo... we might have to choose another package...
Looking 10 minutes into Google i found this: https://github.com/stephanrauh/ngx-extended-pdf-viewer
The only thing that bothers me is, that the bundle size is significantly larger than this one.

Also that project is maintained, so I might give it a try.

**Comment by codehippie1** [comment]
Please send in a pull request with angular upgrade if you can. I will merge and give you a build.

**Comment by rogerfar** [comment]
@konstantinschuette @pmenze I switched to https://github.com/VadimDez/ng2-pdf-viewer

**Comment by pmenze** [comment]
> Please send in a pull request with angular upgrade if you can. I will merge and give you a build.

I tried to update your repo to ng13. The SampleApp worked using ng13 (using the "ng2-pdfjs-viewer-6.0.1.tgz" file). However I could not update the build itself... the gulp script refers to the angular compiler which seems not to work in ng13...
https://github.com/intbot/ng2-pdfjs-viewer/blob/e4afd8ee44c76f8d44fdd17f48142dc613826c7c/gulpfile.js#L4

Maybe the project could be changed to use standard angular build tools for libraries instead of gulp?

**Comment by konstantinschuette** [comment]
> > Please send in a pull request with angular upgrade if you can. I will merge and give you a build.
> 
> I tried to update your repo to ng13. The SampleApp worked using ng13 (using the "ng2-pdfjs-viewer-6.0.1.tgz" file). However I could not update the build itself... the gulp script refers to the angular compiler which seems not to work in ng13...
> 
> https://github.com/intbot/ng2-pdfjs-viewer/blob/e4afd8ee44c76f8d44fdd17f48142dc613826c7c/gulpfile.js#L4
> 
> Maybe the project could be changed to use standard angular build tools for libraries instead of gulp?

Thanks for trying but I think this project is dead.
I will switch to https://github.com/stephanrauh/ngx-extended-pdf-viewer

**Comment by codehippie1** [comment]
@konstantinschuette @pmenze @logerk46 @AnsonWooNexify @spikensbror @ankurkoul92 I upgraded the whole thing to use latest ng-packager. It's more lean and abides latest angular packaging standards. - And works with all angular versions. I started versioning the package to match angular versions(Current is 13.2.2) which it has a peer dependency on.

Test it and let me know.

Again - Sorry for the late reply, getting covid and focusing on a non-profit took some time away from this project. Rest assured, I am here if you need any help.

Coming up - Smaller package size
Parameterized configurations

**Comment by shash7976** [comment]
Hi @codehippie1,
Hope you are doing great now

I'm still facing this compatibility issue on the server 

`4:11:06 PM: npm ERR!     peer @angular/animations@"^13.0.0 || ^14.0.0-0" from @angular/material@13.0.3
4:11:06 PM: npm ERR!     node_modules/@angular/material
4:11:06 PM: npm ERR!       @angular/material@"~13.0.3" from the root project
4:11:06 PM: npm ERR!     1 more (@angular/platform-browser)
4:11:06 PM: npm ERR!   13 more (@angular/cdk, @angular/common, @angular/forms, ...)
4:11:06 PM: npm ERR!
4:11:06 PM: npm ERR! Could not resolve dependency:
4:11:06 PM: npm ERR! peer @angular/core@"<=11" from ng2-pdfjs-viewer@6.0.2
4:11:06 PM: npm ERR! node_modules/ng2-pdfjs-viewer
4:11:06 PM: npm ERR!   ng2-pdfjs-viewer@"^6.0.2" from the root project
4:11:06 PM: npm ERR!
4:11:06 PM: npm ERR! Conflicting peer dependency: @angular/core@11.2.14
4:11:06 PM: npm ERR! node_modules/@angular/core
4:11:06 PM: npm ERR!   peer @angular/core@"<=11" from ng2-pdfjs-viewer@6.0.2
4:11:06 PM: npm ERR!   node_modules/ng2-pdfjs-viewer
4:11:06 PM: npm ERR!     ng2-pdfjs-viewer@"^6.0.2" from the root project
4:11:06 PM: npm ERR!
4:11:06 PM: npm ERR! Fix the upstream dependency conflict, or retry
4:11:06 PM: npm ERR! this command with --force, or --legacy-peer-deps
4:11:06 PM: npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
4:11:06 PM: npm ERR!
4:11:06 PM: npm ERR! See /opt/buildhome/.npm/eresolve-report.txt for a full report.
4:11:06 PM: npm ERR! A complete log of this run can be found in:
4:11:06 PM: npm ERR!     /opt/buildhome/.npm/_logs/2022-05-02T06_11_03_794Z-debug-0.log
4:11:06 PM: Error during NPM install`

Package.json contain 
"ng2-pdfjs-viewer": "^6.0.2",

if I run npm update ng2-pdfjs-viewer on my local machine I get an error 
`npm ERR! Found: @angular/core@13.0.3
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"~13.0.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"<=11" from ng2-pdfjs-viewer@6.0.2
npm ERR! node_modules/ng2-pdfjs-viewer
npm ERR!   ng2-pdfjs-viewer@"^6.0.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.`

Could you please let me know what can be done...
All our production deployments are failing due to this issue

TIA

**Comment by codehippie1** [comment]
Which version are you using?

**Comment by codehippie1** [comment]
Are you on latest version? I don't see any peer dependency to older packages
![image](https://user-images.githubusercontent.com/18332214/166587754-a4007cf6-606b-40e0-8818-089b5fdca274.png)

**Comment by codehippie1** [comment]
Also - this is a closed issue, create another one.

**Comment by shash7976** [comment]
yep created one
Thanks
