### ISSUE TITLE
Upgrade to angular v7

### ISSUE THREAD

**Issue by Jefiozie** [intbot/ng2-pdfjs-viewer#20]
Hi,

Will this libary be update to the new angular version '7' soon?

Thanks!

**Comment by codehippie1** [comment]
@Jefiozie This is underway. A new version will be available soon.

**Comment by MarkPieszak** [comment]
Was this one updated in the latest commits by any chance?
I was looking through them but I wasn't sure - just wanted to double check! @codehippie1

**Comment by codehippie1** [comment]
@MarkPieszak - Big fan. I am honored and humbled to have you write to me. Most of my new projects are built around your aspnetcore angular repos.

To answer your question, YES - It is updated to angular 7. Though I finished implementation, since it is being Memorial day weekend, I didn't get a chance to update till now.

**Comment by codehippie1** [comment]
As per the above comment, this is completed. Hence closing this issue.

**Comment by MarkPieszak** [comment]
Thank you for the kind words @codehippie1 	!! 🙏 	
It makes me so happy to hear that!

If you have any public apps built with it shoot me some links I'd love to take a look!

Thanks so much, I can switch over to use this Lib now :)

You rock 🎸

**Comment by codehippie1** [comment]
@MarkPieszak I used your aspnetcore angular repo for most of my projects at work, and since I work for a govt org, I do not have a public facing portal/nor opensource code which I can share with you.

But to give you an idea of how I used your repos, and I did stretch it as much as I can
1. Built an app couple of years back where web project based on your repo(aspnet core), where all referenced dlls are of .net 4.5, hooked up to keno and kendo bootstrap angular theming(SASS), where one of the 4.5 projects talks to an oracle db using Devart dot connect(Oracle didn't had a driver for EF core then - not sure will they ever have).
Here is an SO question by me trying this crazy combination - (https://stackoverflow.com/questions/45718265/aspnetcore-2-0-with-ef6-and-dotconnect-for-oracle)

2. Used for a second one recently(I am building it now) - Azure B2B auth, azure build and release pipelines, SQL server on cloud with EF core and angular 7 using your repo as a start. Azure tfs builds are failing though, exactly as the problem described here. (None of the suggested solutions worked)
https://developercommunity.visualstudio.com/content/problem/398343/azure-devops-pipeline-fatal-error-ineffective-mark.html

In short, I stretched your core framework (thanks a ton for it and it is an amazing project makes life of peasants like me easy) to talk and dance with azure, elmah.io, custom EF core code generations, T4 templates, SignarR(I can't recall if I added signalr or it was already there), kendo, bootstrap, angular material, microsoft graph api, veracode and so forth

If you would like to see specific portions of code(startup.cs or appmodule and such), I will be able to post them here after removing all sensitive information.

There are few minor concerns though
1. Upgrading to a latest version of your repo is always difficult, as it is not very easy to track changes and merge those changes to an existing project which may have altered the same files(I know this would definitely be very difficult to address)
2. Is it possible to have the starter installed in steps? Such as I am able to choose if I want PWA support or SpaDbContext based sample controller etc and omit what I don't want(like yarn)
3. I had an opportunity to talk to Thomas who is the creator of elmah.io and he mentioned that
"UseElmahIo needs to be called just before UseMvc but after the other calls. It looks a bit weird to be that you call UseExceptionHandler after UseMvc. I don't think it's done this way in the template, but I may remember wrong here". I eventually switched the calls and plugged in `app.UseElmahIo();` between `UseExceptionHandler()` and `UseMvc()`
