### ISSUE TITLE
how to bind event download on click?

### ISSUE THREAD

**Issue by sokhomhuy** [intbot/ng2-pdfjs-viewer#56]
i don't found any docs in this repository for event download pdf it just on print button?
please any one help me.
thanks u in advance,

**Comment by codehippie1** [comment]
@sokhomhuy If you are trying to download manually, there will be a download button in viewer. For auto download refer to `[startDownload]` option. 

A working demo is here: https://ng2-pdfjs-viewer.azurewebsites.net/autodownload

This is a how to question rather than an Issue, Please ask such questions on StackOverflow, which would benefit the community.
