### ISSUE TITLE
Getting error while loading pdf in a viewer 'X-Frame-Options' to 'deny'.

### ISSUE THREAD

**Issue by Kiran-GitHuber** [intbot/ng2-pdfjs-viewer#86]
Getting below error while running in tomcat server but works fine with the local node server.

Refused to display 'myserverpath/assets/pdfjs/web/viewer.html?file=myblobpath&openFile=false&download=true&viewBookmark=true&startPage=0&stopPage=466' in a frame because it set 'X-Frame-Options' to 'deny'.\

Based on couple of suggestions tried below options
1) From serverside changed response header X-Frame-Options to "SAMEORIGIN".Still i am getting the same error.
2) Added filter inside web.xml in tomcat config. Still issue persists
![image](https://user-images.githubusercontent.com/21022883/78980670-0166f400-7b3c-11ea-859a-adf7b1b69dee.png)

**Comment by dedaimia** [comment]
I'm seeing the same issue using ng2-pdfjs-viewer for an angular app that is bundled with a java Spring app (in a war) and deployed to tomcat.

**Comment by codehippie1** [comment]
@dedaimia @Kiran-GitHuber do you have code prevents iframes from properly functioning?

**Comment by dedaimia** [comment]
@codehippie1 not explicit code no.   As web servers and server-side technologies become increasingly more security-conscious, they are likely to have the "X-Frame-Options" header set to "DENY" by default.    Which yes, instructs the web browser not to display content in frames - so that a malicious actor can't display your site inside another website for "clickjacking" attacks.     

For now we are still using the ng2pdfjs viewer, and have (successfully) changed the server side to set "X-Frame-Options" to "SAMEORIGIN" for the ng2pdfjs assets (and underlying pdf.js, which I believe is where the frames use occurs).  Longer term we will probably look for a different pdf viewer that does not require frames.

Karen noted at unsuccessfully attempt to change this same header (looks like in tomcat config) above.   In my case we found we had to change in the server-side (spring boot) code - Spring Boot also sets X-Frame-Options to "DENY" by default, even if server config says otherwise.      It was definitely non-trivial to find who was applying the filter as both web server and various levels of server-side code can be doing it, depending on your technology stack.
